<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer        $this
 * @var \Midnight\CmsModule\Menu\MenuInterface $menu
 * @var integer                                $maxDepth
 */
?>
<h1>Edit menu</h1>
<ul class="page-options">
    <li>
        <a href="<?= $this->url('zfcadmin/cms/menu/create_item', array('menu_id' => $menu->getId())) ?>">
            Create new entry&hellip;
        </a>
    </li>
</ul>
<ul>
    <?php
    $itemPartial = 'midnight/cms-module/menu/menu-admin/edit/item.phtml';
    $index = 0;
    ?>
    <?php foreach ($menu->getItems() as $item): ?>
        <?php
        $params = array(
            'menu' => $menu,
            'item' => $item,
            'path' => array($index),
            'level' => 0,
            'maxDepth' => $maxDepth
        );
        ?>
        <?= $this->partial($itemPartial, $params) ?>
        <?php
        $index += 1;
        ?>
    <?php endforeach ?>
    <li>
        <?php
        $createUrl = $this->url(
            'zfcadmin/cms/menu/create_item',
            array('menu_id' => $menu->getId()),
            array('query' => array('path' => (string)$index))
        );
        ?>
        <a href="<?= $createUrl ?>">
            Create new item&hellip;
        </a>
    </li>
</ul>
