<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer                       $this
 * @var \Midnight\Page\PageInterface                          $page
 * @var \Midnight\CmsModule\Service\BlockTypeManagerInterface $blockTypeManager
 */
$createBlockUrl = $this->url('zfcadmin/cms/block/create', array(), array('query' => array('page_id' => $page->getId())));
$viewUrl = $this->url('cms_page', array('slug' => $page->getSlug()));
$this->headLink()->appendStylesheet($this->basePath('css/midnight/cms-module/admin/page.css'));
?>
<div class="edit-page">
    <h1><?= $page->getName() ?></h1>
    <ul class="page-options">
        <li>
            <a href="<?= $viewUrl ?>">View page</a>
        </li>
        <li>
            <a href="<?= $createBlockUrl ?>">Add block&hellip;</a>
        </li>
    </ul>
    <?= $this->render('midnight/cms-module/page-admin/edit/blocks.phtml', array('page' => $page, 'typeManager' => $blockTypeManager)) ?>
</div>
