<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Midnight\Page\PageInterface[]  $pages
 */
?>
<h1>Pages</h1>
<ul class="page-options">
    <li>
        <a href="<?= $this->url('zfcadmin/cms/page/create') ?>">Seite erstellen&hellip;</a>
    </li>
</ul>
<table>
    <thead>
    <tr>
        <th>Name</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($pages as $page): ?>
        <?php
        $editUrl = $this->url('zfcadmin/cms/page/edit', array('page_id' => $page->getId()));
        $deleteUrl = $this->url('zfcadmin/cms/page/delete', array('page_id' => $page->getId()));
        ?>
        <tr>
            <td>
                <a href="<?= $editUrl ?>"><?= $page->getName() ?></a>
            </td>
            <td>
                <a href="<?= $deleteUrl ?>" class="confirm">Delete</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
