<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Midnight\Page\PageInterface    $page
 * @var \Midnight\Block\BlockInterface  $prevBlock
 */
$prevBlock = null;
?>
<ul class="blocks">
    <?php foreach ($page->getBlocks() as $block): ?>
        <li>
            <?php
            $options = $this->partial('midnight/cms-module/page-admin/edit/block-options.phtml', array(
                'block' => $block,
                'page' => $page,
                'prevBlock' => $prevBlock,
            ));
            ?>
            <?= $options ?>
            <?= $this->blockPreview($block) ?>
            <?php
            $prevBlock = $block;
            ?>
        </li>
    <?php endforeach ?>
</ul>
