<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer                         $this
 * @var \Midnight\CmsModule\InlineBlockOption\OptionInterface[] $options
 */
$this->headScript()->appendFile($this->basePath('js/midnight/cms-module/page.js'));
?>
<ul class="options">
    <?php foreach ($options as $option): ?>
        <?php
        $class = $option->getClass();
        $classString = $class ? ' class="' . $class . '"' : '';
        ?>
        <li>
            <a href="<?= $option->getHref() ?>"<?= $classString ?>><?= $option->getLabel() ?></a>
        </li>
    <?php endforeach ?>
</ul>
<?php
///**
// * @var \Zend\View\Renderer\PhpRenderer                         $this
// * @var \Midnight\CmsModule\InlineBlockOption\OptionInterface[] $options
// */
//$this->headScript()->appendFile($this->basePath('js/midnight/cms-module/page.js'));
//$editUrl = $this->url(
//    'zfcadmin/cms/block/edit',
//    array('block_id' => $block->getId()),
//    array('query' => array('page_id' => $page->getId()))
//);
//$deleteUrl = $this->url(
//    'zfcadmin/cms/page/delete_block',
//    array('page_id' => $page->getId(), 'block_id' => $block->getId())
//);
//if ($prevBlock) {
//    $upUrl = $this->url(
//        'zfcadmin/cms/page/move_block',
//        array('page_id' => $page->getId(), 'block_id' => $block->getId()),
//        array('query' => array('before' => $prevBlock->getId()))
//    );
//}
?>
