<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer                       $this
 * @var \Midnight\Page\PageInterface                          $page
 * @var \Midnight\Block\BlockInterface                        $prevBlock
 * @var \Midnight\CmsModule\Service\BlockTypeManagerInterface $typeManager
 */
$prevBlock = null;
?>
<ul class="blocks">
    <?php foreach ($page->getBlocks() as $block): ?>
        <li>
            <?php
            $opt = $typeManager->getInlineOptionsProviderFor($block)->getOptions($block, $page);
            ?>
            <?= $this->partial('midnight/cms-module/page-admin/edit/block-options.phtml', array('options' => $opt)) ?>
            <?= $this->blockPreview($block) ?>
            <?php
            $prevBlock = $block;
            ?>
        </li>
    <?php endforeach ?>
</ul>
